# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee5f7a386b91e5417fee50fbe1f7e588e63fc46e3a0cc8f2237dfad471e7f32f669d07c9377499d92648128ad87dc73402b3b7feed0fa62c5cb468a3eae591e

test:
  secret_key_base: 58e8b92aa1f4a591831a7cb7e2123e04eedbd71b3724bd9a3223dc7f470f1205d273a544234e00a5bc982a94e97525f7711faae618d3aac00795337d31bb1b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
